### ISSUE TITLE
SENSITIVE INFORMATION

### ISSUE THREAD

**Issue by tanyongzhi** [tanyongzhi/Makan-Tompang#11]
PLS CENSOR
my LIFE is at STAKE

thx

**Comment by tanyongzhi** [comment]
i'm on it boss

**Comment by tanyongzhi** [comment]
@aspentng pls update sketch
@wanchengphua pls re-upload

**Comment by tanyongzhi** [comment]
@gavin-ng  my water bottle is empty...

**Comment by tanyongzhi** [comment]
### **FASTER PLS MY PRIVACY IS LEAKING**

**Comment by gavin-ng** [comment]
> 
> 
> @gavin-ng my water bottle is empty...

i'm on it BOSS

**Comment by tanyongzhi** [comment]
good job team @wanchengphua @gavin-ng @aspentng
