### ISSUE TITLE
TOO MANY SNACKS

### ISSUE THREAD

**Issue by gavin-ng** [tanyongzhi/Makan-Tompang#12]
pls HELP the organizers to REDUCE food waste

**Comment by gavin-ng** [comment]
@aspentng pls take the DRINKS
@wanchengphua pls TAKE the cokkies
@tanyongzhi good morning BOSS

**Comment by gavin-ng** [comment]
@wanchengphua

**Comment by wanchengphua** [comment]
aspen close pls

**Comment by aspentng** [comment]
sorry didn't have message

good job team #flaskbois #unitybois

**Comment by tanyongzhi** [comment]
#6
